version: "3.4"
services:

# ##########################################################################
# Multi Cloud Shell
# ##########################################################################
  mcs:
    image: mcs:${MCS_VERSION}
    container_name: mcs
    build:
      context: .
      args:
        uid: ${UID}
        gid: ${GID}
    volumes:
      - ./workdir:/home/mcs
    environment:
      - TZ=Europe/Berlin
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - 2222:22
    stdin_open: true
    tty: true
    restart: always
    network_mode: host

# docker build --build-arg uid=$(id -u) --build-arg gid=$(id -g) -t moadsd-ng-server -f Dockerfile .
