#!/bin/bash
echo "\
export ACCOUNT_ID=${ACCOUNT_ID}
export AWS_REGION=${AWS_REGION}
export ROLE_NAME=${ROLE_NAME}
export INSTANCE_PROFILE_NAME=${INSTANCE_PROFILE_NAME}
export MASTER_ARN=${MASTER_ARN}
export CLUSTER_NAME=${CLUSTER_NAME}
export DSSC_NAMESPACE=${DSSC_NAMESPACE}
export DSSC_USERNAME=${DSSC_USERNAME}
export DSSC_PASSWORD=${DSSC_PASSWORD}
export DSSC_REGUSER=${DSSC_REGUSER}
export DSSC_REGPASSWORD=${DSSC_REGPASSWORD}
export DSSC_AC=${DSSC_AC}
export DNS_NAME=${DNS_NAME}
export DSSC_HOST=${DSSC_HOST}
export CODEBUILD_ROLE_NAME=${CODEBUILD_ROLE_NAME}
export APP_NAME=${APP_NAME}
export TREND_AP_KEY=${TREND_AP_KEY}
export TREND_AP_SECRET=${TREND_AP_SECRET}
export IMAGE_NAME=${IMAGE_NAME}
export IMAGE_TAG=${IMAGE_TAG}
" > ~/.aws-lab.sh